const constants = {
  CHANGE_TOPIC: 'CHANGE_TOPIC',
  FORM_INIT: 'FORM_INIT',
  FORM_CLOSE: 'FORM_CLOSE',
  NEWS_INIT: 'NEWS_INIT',
  CHANGE_NEWS_INDEX: 'CHANGE_NEWS_INDEX',
  CHANGE_APP_STATUS: 'CHANGE_APP_STATUS'
};

export default constants;
