const constants = {
  CHANGE_TOPIC: 'CHANGE_TOPIC',
  RESET_TOPIC: 'RESET_TOPIC',
  FORM_INIT: 'FORM_INIT',
  FORM_CLOSE: 'FORM_CLOSE',
  SET_NEWS: 'SET_NEWS',
  RESET_NEWS: 'RESET_NEWS',
  CHANGE_NEWS_INDEX: 'CHANGE_NEWS_INDEX',
  CHANGE_APP_STATUS: 'CHANGE_APP_STATUS'
};

export default constants;
